public enum EventID
{
    NONE,
    START_GAME,
    COMPLETE_LEVEL,
    START_LEVEL,
    CLAIM_DAILY_REWARD,
    EXIT_GAME,
    BUY_PRODUCT_SUCCESS,
    CHANGE_LANGUAGE,
    HINT_CHANGE,

    GO_SETTING,
    GO_SELECT_LEVEL,
    GO_SHOP,

    METEORITE_COLLISION_EARTH
}
